version: "3.8"

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: projeto_base
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "4306:3306"
    volumes:
      - ./backend/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/projeto_base
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "81:80"
    volumes:
      - ./backend:/var/www/projeto_base
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
